---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-kubebrowser-io-v1alpha1-browsersystem
  failurePolicy: Fail
  name: mbrowsersystem-v1alpha.kb.io
  rules:
  - apiGroups:
    - core.kubebrowser.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - browsersystems
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-kubebrowser-io-v1alpha1-browsersystem
  failurePolicy: Fail
  name: vbrowsersystem-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.kubebrowser.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - browsersystems
  sideEffects: None
